# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sp_app", "0039_auto_20170704_1753"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ward",
            name="continued",
        ),
    ]
