# Generated by Django 2.0 on 2018-05-01 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sp_app", "0040_remove_ward_continued"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ward",
            options={
                "ordering": ["position"],
                "verbose_name": "Funktion",
                "verbose_name_plural": "Funktionen",
            },
        ),
        migrations.AddField(
            model_name="ward",
            name="weekdays",
            field=models.CharField(
                default="",
                help_text="Days of the week when this is to be planned. (String of digits, 0  for sunday.)",
                max_length=7,
                verbose_name="weekdays",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="Region (Bundesland), deren Feiertage für dieses Krankenhaus gelten.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="companies",
                to="sp_app.Region",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="anonymous",
            field=models.BooleanField(
                default=False,
                help_text="Diese Person steht für mehrere andere Personen, z.B. eine Abteilung",
                verbose_name="Anonym",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="position",
            field=models.IntegerField(
                default=1,
                help_text="Ordering in the display. Should not be more than two digits.",
                verbose_name="Position",
            ),
        ),
        migrations.AlterField(
            model_name="ward",
            name="after_this",
            field=models.ManyToManyField(
                blank=True,
                help_text="wenn etwas ausgewählt ist, kann der Diensthabende am nächsten Tag nur für diese Funktionen verplant werden",
                to="sp_app.Ward",
                verbose_name="Folgeschicht",
            ),
        ),
        migrations.AlterField(
            model_name="ward",
            name="everyday",
            field=models.BooleanField(
                default=False,
                help_text="Diese Funktion muss auch an freien Tagen geplant werden",
                verbose_name="täglich",
            ),
        ),
        migrations.AlterField(
            model_name="ward",
            name="freedays",
            field=models.BooleanField(
                default=False,
                help_text="Diese Funktion kann nur an freien Tagen geplant werden",
                verbose_name="freie Tage",
            ),
        ),
        migrations.AlterField(
            model_name="ward",
            name="nightshift",
            field=models.BooleanField(
                default=False,
                help_text="Der Diensthabende kann nicht für den nächsten Tag verplant werden",
                verbose_name="Nachtdienst",
            ),
        ),
        migrations.AlterField(
            model_name="ward",
            name="on_leave",
            field=models.BooleanField(
                default=False,
                help_text="Die hier eingetragenen Personen stehen nicht zur Arbeit zur Verfügung",
                verbose_name="Urlaub/frei",
            ),
        ),
        migrations.AlterField(
            model_name="ward",
            name="position",
            field=models.IntegerField(
                default=1,
                help_text="Ordering in the display. Should not be more than two digits.",
            ),
        ),
        migrations.AlterField(
            model_name="ward",
            name="weight",
            field=models.IntegerField(
                default=0,
                help_text="Wenn dies ein Bereitschaftsdienst ist, beschreibt dies die Belastung für den Diensthabenden",
            ),
        ),
    ]
