# Generated by Django 3.1.5 on 2021-05-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sp_app", "0052_auto_20210526_0658"),
    ]

    operations = [
        # intentionally left empty!
    ]
