# Generated by Django 4.0.3 on 2022-05-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_app', '0056_alter_employee_options_alter_ward_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='updateddate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedid',
            name='uid',
            field=models.CharField(max_length=20, unique=True, verbose_name='ID'),
        ),
    ]
