# Generated by Django 4.0.3 on 2022-05-25 09:38

from datetime import date
from django.db import migrations

FAR_FUTURE = date(2099, 12, 31)


def set_approved_if_none(apps, schema_editor):
    Ward = apps.get_model("sp_app", "Ward")
    Ward.objects.filter(approved__isnull=True).update(approved=FAR_FUTURE)


class Migration(migrations.Migration):

    dependencies = [
        ("sp_app", "0057_planning_updateddate_alter_feedid_uid"),
    ]

    operations = [
        migrations.RunPython(set_approved_if_none),
    ]
