# Generated by Django 4.0.3 on 2022-05-25 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_app', '0058_auto_20220525_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='approved',
            field=models.DateField(blank=True, default=datetime.date(2099, 12, 31), help_text='Das Datum, bis zu dem der Plan genehmigt ist', null=True),
        ),
    ]
