# Generated by Django 4.0.3 on 2022-05-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_app', '0059_alter_ward_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Name der Klinik (z.B. "Waldklinik Neustadt")', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='shortname',
            field=models.CharField(help_text='Abkürzung für die Klinik (z.B. "wkns")', max_length=10, verbose_name='Kurzname'),
        ),
        migrations.AlterField(
            model_name='department',
            name='shortname',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Kurzname'),
        ),
    ]
