# Generated by Django 4.0.5 on 2022-07-05 18:17

from django.db import migrations


def make_sites(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Site = apps.get_model("sites", "Site")
    Site.objects.filter(id=1).update(domain="localhost:8000", name="dev")
    Site.objects.create(id=2, domain="stationsplan.de", name="Stationsplan.de")
    Site.objects.create(id=3, domain="stpst.uber.space", name="staging")


class Migration(migrations.Migration):

    dependencies = [
        (
            "sp_app",
            "0062_alter_company_region_alter_employee_departments_and_more",
        ),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RunPython(make_sites),
    ]
