# Generated by Django 4.0.5 on 2022-07-05 18:17

import pdb
from django.db import migrations


def make_sites(apps, schema_editor):

    Site = apps.get_model("sites", "Site")
    Site.objects.update_or_create(
        id=1, defaults={"domain": "localhost:8000", "name": "dev"}
    )
    Site.objects.update_or_create(
        id=2, defaults={"domain": "stationsplan.de", "name": "Stationsplan.de"}
    )
    Site.objects.update_or_create(
        id=3, defaults={"domain": "stpst.uber.space", "name": "staging"}
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "sp_app",
            "0062_alter_company_region_alter_employee_departments_and_more",
        ),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RunPython(make_sites),
    ]
