# Generated by Django 4.0.6 on 2022-07-23 04:23

from django.db import migrations, models
import sp_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sp_app', '0063_make_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='_level',
            field=models.CharField(max_length=20, null=True, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='person',
            name='start_date',
            field=models.DateField(default=sp_app.utils.get_first_of_month, help_text='Dienstantritt', verbose_name='Dienstantritt'),
        ),
        migrations.AlterUniqueTogether(
            name='ward',
            unique_together={('shortname', 'company'), ('name', 'company')},
        ),
    ]
