# Generated by Django 4.0.6 on 2022-07-23 04:28

from django.db import migrations


def save_employee_level(apps, schema_editor):
    Employee = apps.get_model("sp_app", "Employee")
    Group = apps.get_model("auth", "Group")
    g_names = (
        ("is_company_admin", "Company Admin"),
        ("is_dep_lead", "Department admins"),
        ("is_editor", "Editors"),
    )
    groups = dict(
        (perm, Group.objects.get(name=name)) for perm, name in g_names
    )

    for e in Employee.objects.all():
        for level, _ in g_names:
            if e.user.groups.contains(groups[level]):
                e._level = level
                e.save()
                break


class Migration(migrations.Migration):

    dependencies = [
        ("sp_app", "0064_employee__level_alter_person_start_date_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(save_employee_level),
    ]
