# Generated by Django 4.0.6 on 2022-08-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_app', '0065_save_employee_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='on_different_days',
            field=models.BooleanField(default=False, help_text='This function can be planned on different days', verbose_name='on_different_days'),
        ),
    ]
